/* Lucid Reels Media — SINGLE SOURCE OF TRUTH for the portfolio.
   Edit here to add/remove/reorder photos. Item = [file, poster(or null), sourceNote].
   Drives: portfolio-index.html (reference), index.html covers, exterior.html, interior.html.
   Photos live in images/portfolio/ ; videos/posters in images/ . */
window.PORTFOLIO = {
  video: [
  ["project-travilah.mp4", "project-travilah-poster.jpg", "14247 Travilah Road with Jayme Park — Listing Video"],
  ["project-unit306.mp4", "project-unit306-poster.jpg", "Unit 306 with Bryan Galdos — Agent Branding Video"],
  ["project-hilltop.mp4", "project-hilltop-poster.jpg", "300 Hilltop Lane with Chris Fuller — Agent-led Walkthrough"],
  ["project-branded.mp4", "project-branded-poster.jpg", "Branded Marketing with Dasha Nikolenko — Agent Branding Video"],
  ["project-stpetedrone.mp4", "project-stpetedrone-poster.jpg", "St. Pete Drone Shots — Drone & Aerial Video"],
  ["project-ridgewood.mp4", "project-ridgewood-poster.jpg", "6911 Ridgewood Avenue with Dasha and Eric — Agent Branding Video"]
 ],
  exterior: [
  ["gov-01.jpg", null, "37 Governor Markham Dr, Glen Mills PA (Zillow)"],
  ["gov-04.jpg", null, "37 Governor Markham Dr, Glen Mills PA (Zillow)"],
  ["gov-29.jpg", null, "37 Governor Markham Dr, Glen Mills PA (Zillow)"],
  ["gov-31.jpg", null, "37 Governor Markham Dr, Glen Mills PA (Zillow)"],
  ["sea-01.jpg", null, "4400Beach-306_01_4K.png (487.1)"],
  ["sea-16.jpg", null, "4400Beach-306_16_4K.png (487.2)"],
  ["sea-05.jpg", null, "4400Beach-306_05_4K.png (487.7)"],
  ["cav-01.jpg", null, "912.jpg (3817 Central Ave)"],
  ["cav-03.jpg", null, "912.2 (3817 Central Ave)"],
  ["cav-14.jpg", null, "912.13 (3817 Central Ave)"],
  ["cummings-02.jpg", null, "3209 Cummings Ln — AI St. Petersburg FL exterior restyle (front + neighbor)"],
  ["cummings-01.jpg", null, "3209 Cummings Ln — AI St. Petersburg FL exterior restyle (front)"],
  ["cummings-05.jpg", null, "3209 Cummings Ln — AI St. Petersburg FL exterior restyle (rear)"],
  ["st33-05.jpg", null, "6411 33rd St NW (Chevy Chase DC source) — AI St. Petersburg FL Key West Conch restyle (front elevation, straight on)"],
  ["st33-01.jpg", null, "6411 33rd St NW (Chevy Chase DC source) — AI St. Petersburg FL Key West Conch restyle (front hero)"],
  ["st33-13.jpg", null, "6411 33rd St NW (Chevy Chase DC source) — AI St. Petersburg FL Key West Conch restyle (covered porch, view toward neighbour)"],
  ["hill-01.jpg", null, "921 N Hilltop Rd (Virginia Beach source) — AI Tampa / St. Pete Gulf Coast Mediterranean restyle (front three-quarter, HERO)"],
  ["hill-02.jpg", null, "921 N Hilltop Rd (Virginia Beach source) — AI Tampa / St. Pete Gulf Coast Mediterranean restyle (front elevation, wide)"],
  ["hill-05.jpg", null, "921 N Hilltop Rd (Virginia Beach source) — AI Tampa / St. Pete Gulf Coast Mediterranean restyle (entry and front walk)"],
  ["hill-10.jpg", null, "921 N Hilltop Rd (Virginia Beach source) — AI Tampa / St. Pete Gulf Coast Mediterranean restyle (back garden)"],
  ["cap-02.jpg", null, "322 Captains Cir (Lewes DE source) — AI Tampa / St. Pete coquina & cypress coastal restyle (front elevation, wide)"],
  ["cap-03.jpg", null, "322 Captains Cir (Lewes DE source) — AI Tampa / St. Pete coquina & cypress coastal restyle (front elevation at dusk)"],
  ["cap-04.jpg", null, "322 Captains Cir (Lewes DE source) — AI Tampa / St. Pete coquina & cypress coastal restyle (low aerial, front three-quarter)"],
  ["cap-05.jpg", null, "322 Captains Cir (Lewes DE source) — AI Tampa / St. Pete coquina & cypress coastal restyle (aerial over the house)"],
  ["cap-12.jpg", null, "322 Captains Cir (Lewes DE source) — AI Tampa / St. Pete coquina & cypress coastal restyle (rear garden)"],
  ["cap-10.jpg", null, "322 Captains Cir (Lewes DE source) — AI Tampa / St. Pete coquina & cypress coastal restyle (screened porch, second view)"]
 ],
  interior: [
  ["gov-08.jpg", null, "gov-08_south_int_master.png — AI Modern Southern Transitional restyle (37 Governor Markham Dr, Glen Mills PA)"],
  ["gov-12.jpg", null, "gov-12_south_int_master.png — AI Modern Southern Transitional restyle (37 Governor Markham Dr, Glen Mills PA)"],
  ["gov-13.jpg", null, "gov-13_south_int_master.png — AI Modern Southern Transitional restyle (37 Governor Markham Dr, Glen Mills PA)"],
  ["gov-17.jpg", null, "gov-17_south_int_master.png — AI Modern Southern Transitional restyle (37 Governor Markham Dr, Glen Mills PA)"],
  ["gov-20.jpg", null, "gov-20_south_int_master.png — AI Modern Southern Transitional restyle (37 Governor Markham Dr, Glen Mills PA)"],
  ["gov-21.jpg", null, "gov-21_south_int_master.png — AI Modern Southern Transitional restyle (37 Governor Markham Dr, Glen Mills PA)"],
  ["gov-24.jpg", null, "gov-24_south_int_master.png — AI Modern Southern Transitional restyle (37 Governor Markham Dr, Glen Mills PA)"],
  ["cav-18.jpg", null, "912.17 (3817 Central Ave)"],
  ["cav-11.jpg", null, "912.10 (3817 Central Ave)"],
  ["cav-22.jpg", null, "912.21 (3817 Central Ave)"],
  ["cav-19.jpg", null, "912.18 (3817 Central Ave)"],
  ["cav-17.jpg", null, "912.16 (3817 Central Ave)"],
  ["ph-02.jpg", null, "Home 3/detail-photo-5.jpg"],
  ["ph-04.jpg", null, "Home 3/detail-photo-18.jpg"],
  ["cav-09.jpg", null, "912.8 (3817 Central Ave)"],
  ["ph-05.jpg", null, "Home 3/detail-photo-25.jpg"],
  ["ph-06.jpg", null, "Home 3/detail-photo-33.jpg"],
  ["sea-10.jpg", null, "4400Beach-306_10_4K.png (487.17)"],
  ["sea-08.jpg", null, "4400Beach-306_08_4K.png (487.15)"],
  ["sea-07.jpg", null, "4400Beach-306_07_4K.png (487.14)"],
  ["sea-20.jpg", null, "4400Beach-306_20_4K.png (487.10)"],
  ["sea-04.jpg", null, "4400Beach-306_04_4K.png (487.6)"],
  ["vstage-01.jpg", null, "vstage-01_organic_master.png — AI Warm Modern Organic (Sage & Stone) restage"],
  ["vstage-05.jpg", null, "vstage-05_organic_master.png — AI Warm Modern Organic (Sage & Stone) restage"],
  ["vstage-08.jpg", null, "vstage-08_organic_master.png — AI Warm Modern Organic (Sage & Stone) restage"],
  ["vstage-10.jpg", null, "vstage-10_organic_master.png — AI Warm Modern Organic (Sage & Stone) restage"],
  ["vstage-12.jpg", null, "vstage-12_organic_master.png — AI Warm Modern Organic (Sage & Stone) restage"],
  ["cav-10.jpg", null, "912.9 (3817 Central Ave)"],
  ["cav-20.jpg", null, "912.19 (3817 Central Ave)"],
  ["cav-21.jpg", null, "912.20 (3817 Central Ave)"]
 ]
};
